### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by caarlos0** [caarlos0-graveyard/java-best-practices#8]
We need to define a way to better organize all this. If we still adding things to the plain README.md file, it will became giant.

My suggestion: Organize it in a Jekyll tree and generate the pages or, maybe, another tool to convert and publicity it somehow somewhere. We can try to automate the build/deploy via travis-ci, in the worst case scenario.

What do you think?

**Comment by antonini** [comment]
I think is a good idea to do that. Separete the subjects by category and have some tags on the topics would be nice to index the content.

**Comment by caarlos0** [comment]
We also have to define the subjects.

Example:
- basics
  - syntax
  - exceptions
  - 120c
  - whitespaces
  - other language basics
- JPA
  - sub topics
- EJB (?)
  - sub topics

what else?

**Comment by antonini** [comment]
Copied your example and improved a little bit.

Example:
- Basics
  - syntax
  - exceptions
  - 120c
  - whitespaces
  - other language basics
- JEE
  - JPA
    - sub topics
  - EJB
    - Stateless
    - statefull
    - MessageDriven
- Patterns
  - Design Patterns (GOF)
  - J2EE Patterns

what else?

**Comment by caarlos0** [comment]
- Basics
  - syntax
  - exceptions
  - 120c
  - whitespaces
  - other language basics
- JEE
  - JPA
    - sub topics
  - EJB
    - Stateless
    - statefull
    - MessageDriven
    - CDI
- Patterns
  - Design Patterns (GOF)
  - J2EE Patterns

Just added CDI :palm_tree: 

@lucasmerencia knows a lot about patterns and Java EE, he will surely help a lot :dancers:

**Comment by merencia** [comment]
CDI is powerfull but I think we can talk about dependency injection and inversion of control first.

BTW: We can also use wiki pages

**Comment by caarlos0** [comment]
nice!

yes, but wiki is kinda hard to maintain...

On Tue, Jul 23, 2013 at 3:38 PM, Lucas José Merencia <
notifications@github.com> wrote:

> CDI is powerfull but I think we can talk about dependency injection and
> inversion of control first.
> 
> BTW: We can also use wiki pages
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/caarlos0/java-best-practices/issues/8#issuecomment-21436195
> .

## 

Best regards,
_Carlos Alexandro Becker_
http://carlosbecker.com/about

**Comment by antonini** [comment]
That's true... maintain a wiki page... puff is so hard... I think if we organize that similiar as a "book" it would be easier to maintain.

**Comment by caarlos0** [comment]
Yeap, I'm thinking about use Jekyll or even a damn simple Sinatra app with a continuous deploy to heroku via travis-ci.

It will probably fit good :)

**Comment by caarlos0** [comment]
Finally made it work, but it's using Angular.js.

I can improve it to support sub-folders too :)

**Comment by caarlos0** [comment]
btw: http://carlosbecker.com/java-best-practices/
