### ISSUE TITLE
String concatenation

### ISSUE THREAD

**Issue by gmcoringa** [caarlos0-graveyard/java-best-practices#9]
Some corrections.
The use of + on string concatenation does not create a StringBuilder per +, but a single StringBuilder replacing all + with append method.
A simple test: create a method with + concatenation and decompile the class or debug it.

**Comment by caarlos0** [comment]
true that, sorry.

**Comment by caarlos0** [comment]
I believe that it's right now. I accidentally commit directly to master ¬¬

Can you take a look?

**Comment by luizkowalski** [comment]
*\* accidentally **

**Comment by caarlos0** [comment]
really, dude, I was sure I had created a branch...

**Comment by luizkowalski** [comment]
◔_◔
